# Generated by Django 2.2 on 2020-02-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='notes',
        ),
    ]
